fs = require 'fs'
exec = require('child_process').exec

{print} = require 'util'
{spawn} = require 'child_process'

build = (callback) ->
  coffee = spawn 'coffee', ['--join', 'resources/js/gb.js', '--compile',
    'coffee/jquery.cookie.js',
    'coffee/jquery.mousewheel.js',
    'coffee/slimScroll.js',
    'coffee/geom.coffee',
    'coffee/vec3mat4x4.coffee',
    'coffee/Quaternion.coffee',
    'coffee/alerts.coffee',
    'coffee/interface.coffee',
    'coffee/Node.coffee',
    'coffee/SphericalCoords.coffee',
    'coffee/SNode.coffee',
    'coffee/Link.coffee',
    'coffee/layout.coffee',
    'coffee/Graph.coffee',
    'coffee/search.coffee',
    'coffee/user.coffee',
    'coffee/add.coffee',
    'coffee/remove.coffee',
    'coffee/brain.coffee',
    'coffee/friend.coffee',
    'coffee/main.coffee']
  coffee.stderr.on 'data', (data) ->
    process.stderr.write data.toString()
  coffee.stdout.on 'data', (data) ->
    print data.toString()
  coffee.on 'exit', (code) ->
    callback?() if code is 0

css = (callback) ->
  cat = exec 'cat css/main.css css/interface.css css/links.css css/nodes.css > resources/css/main.css', (error, stdout, stderr) =>
    print stdout
    process.stderr.write stderr
    if error isnt null
      console log error

task 'build', 'Compile CoffeeScript files', ->
  build()

task 'css', 'Concatenate CSS files', ->
  css()