fs = require 'fs'
exec = require('child_process').exec

{print} = require 'util'
{spawn} = require 'child_process'

build = (callback) ->
  coffee = spawn 'coffee', ['--join', 'resources/js/gb.js', '--compile',
    'coffee/aux.coffee',
    'coffee/geom.coffee',
    'coffee/vec3mat4x4.coffee',
    'coffee/quat.coffee',
    'coffee/visualobj.coffee',
    'coffee/node.coffee',
    'coffee/snode.coffee',
    'coffee/link.coffee',
    'coffee/graph.coffee',
    'coffee/main.coffee']
  coffee.stderr.on 'data', (data) ->
    process.stderr.write data.toString()
  coffee.stdout.on 'data', (data) ->
    print data.toString()
  coffee.on 'exit', (code) ->
    callback?() if code is 0

css = (callback) ->
  cat = exec 'cat css/main.css css/dialog.css css/interface.css css/links.css css/nodes.css > resources/css/main.css', (error, stdout, stderr) =>
    print stdout
    process.stderr.write stderr
    if error isnt null
      console log error

task 'build', 'Compile CoffeeScript files', ->
  build()

task 'css', 'Concatenate CSS files', ->
  css()