from gb.hypergraph import *
from gb.inference.rules import Rules


rules = Rules()

predicates = {'says/nlp.say.verb': {'3': True,
                                    '4': False,
                                    'actor': True,
                                    'claim': True,
                                    'conflict': False},
              'is/nlp.be.verb': {'3': True,
                                 '4': False,
                                 'actor': False,
                                 'claim': False,
                                 'conflict': False},
              'kills/nlp.kill.verb': {'3': True,
                                      '4': True,
                                      'actor': False,
                                      'claim': False,
                                      'conflict': True},
              'killed/nlp.kill.verb': {'3': False,
                                       '4': False,
                                       'actor': False,
                                       'claim': False,
                                       'conflict': False},
              'warns/nlp.warn.verb': {'3': True,
                                      '4': True,
                                      'actor': True,
                                      'claim': False,
                                      'conflict': True},
              'calls/nlp.call.verb': {'3': True,
                                      '4': True,
                                      'actor': True,
                                      'claim': False,
                                      'conflict': False},
              'said/nlp.say.verb': {'3': True,
                                    '4': False,
                                    'actor': True,
                                    'claim': True,
                                    'conflict': False},
              'say/nlp.say.verb': {'3': True,
                                   '4': False,
                                   'actor': True,
                                   'claim': True,
                                   'conflict': False},
              'found/nlp.find.verb': {'3': False,
                                      '4': False,
                                      'actor': False,
                                      'claim': False,
                                      'conflict': False},
              'arrested/nlp.arrest.verb': {'3': False,
                                           '4': False,
                                           'actor': False,
                                           'claim': False,
                                           'conflict': False},
              'kill/nlp.kill.verb': {'3': True,
                                     '4': False,
                                     'actor': True,
                                     'claim': False,
                                     'conflict': True},
              'are/nlp.be.verb': {'3': True,
                                  '4': False,
                                  'actor': False,
                                  'claim': False,
                                  'conflict': False},
              'dies/nlp.die.verb': {'3': False,
                                    '4': False,
                                    'actor': False,
                                    'claim': False,
                                    'conflict': False},
              'hits/nlp.hit.verb': {'3': False,
                                    '4': False,
                                    'actor': False,
                                    'claim': False,
                                    'conflict': False},
              'accuses/nlp.accuse.verb': {'3': False,
                                          '4': True,
                                          'actor': True,
                                          'claim': False,
                                          'conflict': True},
              'bans/nlp.ban.verb': {'3': True,
                                    '4': True,
                                    'actor': True,
                                    'claim': False,
                                    'conflict': False},
              'has/nlp.have.verb': {'3': False,
                                    '4': False,
                                    'actor': False,
                                    'claim': False,
                                    'conflict': False},
              'rejects/nlp.reject.verb': {'3': True,
                                          '4': True,
                                          'actor': True,
                                          'claim': False,
                                          'conflict': False},
              'gets/nlp.get.verb': {'3': False,
                                    '4': False,
                                    'actor': False,
                                    'claim': False,
                                    'conflict': False},
              'accused/nlp.accuse.verb': {'3': True,
                                          '4': False,
                                          'actor': True,
                                          'claim': False,
                                          'conflict': False},
              'finds/nlp.find.verb': {'3': False,
                                      '4': False,
                                      'actor': False,
                                      'claim': False,
                                      'conflict': False},
              'faces/nlp.face.verb': {'3': False,
                                      '4': False,
                                      'actor': False,
                                      'claim': False,
                                      'conflict': False},
              'seeks/nlp.seek.verb': {'3': False,
                                      '4': False,
                                      'actor': False,
                                      'claim': False,
                                      'conflict': False},
              'approves/nlp.approve.verb': {'3': True,
                                            '4': False,
                                            'actor': True,
                                            'claim': False,
                                            'conflict': False},
              'launches/nlp.launch.verb': {'3': False,
                                           '4': False,
                                           'actor': False,
                                           'claim': False,
                                           'conflict': False},
              'hit/nlp.hit.verb': {'3': False,
                                   '4': False,
                                   'actor': False,
                                   'claim': False,
                                   'conflict': False},
              'threatens/nlp.threaten.verb': {'3': False,
                                              '4': False,
                                              'actor': False,
                                              'claim': False,
                                              'conflict': False},
              'shows/nlp.show.verb': {'3': False,
                                      '4': False,
                                      'actor': False,
                                      'claim': False,
                                      'conflict': False},
              'was/nlp.be.verb': {'3': True,
                                  '4': False,
                                  'actor': False,
                                  'claim': False,
                                  'conflict': False},
              'makes/nlp.make.verb': {'3': False,
                                      '4': False,
                                      'actor': False,
                                      'claim': False,
                                      'conflict': False},
              'Õs/nlp.Õs.part': {'3': False,
                                 '4': False,
                                 'actor': False,
                                 'claim': False,
                                 'conflict': False},
              'takes/nlp.take.verb': {'3': False,
                                      '4': False,
                                      'actor': False,
                                      'claim': False,
                                      'conflict': False},
              'announces/nlp.announce.verb': {'3': True,
                                              '4': False,
                                              'actor': True,
                                              'claim': False,
                                              'conflict': False},
              'claims/nlp.claim.verb': {'3': True,
                                        '4': False,
                                        'actor': True,
                                        'claim': True,
                                        'conflict': False},
              'wins/nlp.win.verb': {'3': True,
                                    '4': False,
                                    'actor': True,
                                    'claim': False,
                                    'conflict': False},
              'sentenced/nlp.sentence.verb': {'3': False,
                                              '4': False,
                                              'actor': False,
                                              'claim': False,
                                              'conflict': False},
              'reveals/nlp.reveal.verb': {'3': False,
                                          '4': False,
                                          'actor': False,
                                          'claim': False,
                                          'conflict': False},
              'condemns/nlp.condemn.verb': {'3': True,
                                            '4': True,
                                            'actor': True,
                                            'claim': False,
                                            'conflict': True},
              'confirms/nlp.confirm.verb': {'3': True,
                                            '4': True,
                                            'actor': True,
                                            'claim': False,
                                            'conflict': False},
              'declares/nlp.declare.verb': {'3': True,
                                            '4': False,
                                            'actor': True,
                                            'claim': False,
                                            'conflict': False},
              'gives/nlp.give.verb': {'3': False,
                                      '4': False,
                                      'actor': False,
                                      'claim': False,
                                      'conflict': False},
              'slams/nlp.slam.verb': {'3': True,
                                      '4': True,
                                      'actor': True,
                                      'claim': False,
                                      'conflict': True},
              'offers/nlp.offer.verb': {'3': False,
                                        '4': False,
                                        'actor': False,
                                        'claim': False,
                                        'conflict': False},
              'sends/nlp.send.verb': {'3': False,
                                      '4': False,
                                      'actor': False,
                                      'claim': False,
                                      'conflict': False},
              'denies/nlp.deny.verb': {'3': True,
                                       '4': False,
                                       'actor': True,
                                       'claim': False,
                                       'conflict': False},
              "('says/nlp.say.verb', 'is/nlp.be.verb')": {'3': False,
                                                          '4': False,
                                                          'actor': False,
                                                          'claim': False,
                                                          'conflict': False},
              'sees/nlp.see.verb': {'3': False,
                                    '4': False,
                                    'actor': False,
                                    'claim': False,
                                    'conflict': False},
              'urges/nlp.urge.verb': {'3': False,
                                      '4': False,
                                      'actor': False,
                                      'claim': False,
                                      'conflict': False},
              'wants/nlp.want.verb': {'3': True,
                                      '4': False,
                                      'actor': True,
                                      'claim': False,
                                      'conflict': False},
              'opens/nlp.open.verb': {'3': False,
                                      '4': False,
                                      'actor': False,
                                      'claim': False,
                                      'conflict': False},
              'raises/nlp.raise.verb': {'3': False,
                                        '4': False,
                                        'actor': False,
                                        'claim': False,
                                        'conflict': False},
              'suspends/nlp.suspend.verb': {'3': False,
                                            '4': False,
                                            'actor': False,
                                            'claim': False,
                                            'conflict': False},
              'jailed/nlp.jail.verb': {'3': False,
                                       '4': False,
                                       'actor': False,
                                       'claim': False,
                                       'conflict': False},
              'arrest/nlp.arrest.verb': {'3': True,
                                         '4': True,
                                         'actor': True,
                                         'claim': False,
                                         'conflict': True},
              'passes/nlp.pass.verb': {'3': False,
                                       '4': False,
                                       'actor': False,
                                       'claim': False,
                                       'conflict': False},
              'take/nlp.take.verb': {'3': False,
                                     '4': False,
                                     'actor': False,
                                     'claim': False,
                                     'conflict': False},
              'shot/nlp.shoot.verb': {'3': False,
                                      '4': False,
                                      'actor': False,
                                      'claim': False,
                                      'conflict': False},
              'goes/nlp.go.verb': {'3': False,
                                   '4': False,
                                   'actor': False,
                                   'claim': False,
                                   'conflict': False},
              'begins/nlp.begin.verb': {'3': False,
                                        '4': False,
                                        'actor': False,
                                        'claim': False,
                                        'conflict': False},
              'charged/nlp.charge.verb': {'3': True,
                                          '4': False,
                                          'actor': True,
                                          'claim': False,
                                          'conflict': False},
              'blames/nlp.blame.verb': {'3': True,
                                        '4': True,
                                        'actor': True,
                                        'claim': False,
                                        'conflict': True},
              'arrests/nlp.arrest.verb': {'3': True,
                                          '4': True,
                                          'actor': True,
                                          'claim': False,
                                          'conflict': True},
              'plans/nlp.plan.verb': {'3': True,
                                      '4': False,
                                      'actor': True,
                                      'claim': False,
                                      'conflict': False},
              'find/nlp.find.verb': {'3': False,
                                     '4': False,
                                     'actor': False,
                                     'claim': False,
                                     'conflict': False},
              'becomes/nlp.become.verb': {'3': False,
                                          '4': False,
                                          'actor': False,
                                          'claim': False,
                                          'conflict': False},
              'seize/nlp.seize.verb': {'3': False,
                                       '4': False,
                                       'actor': False,
                                       'claim': False,
                                       'conflict': False},
              'reported/nlp.report.verb': {'3': False,
                                           '4': False,
                                           'actor': False,
                                           'claim': False,
                                           'conflict': False},
              'defends/nlp.defend.verb': {'3': True,
                                          '4': True,
                                          'actor': True,
                                          'claim': False,
                                          'conflict': False},
              'leaves/nlp.leave.verb': {'3': False,
                                        '4': False,
                                        'actor': False,
                                        'claim': False,
                                        'conflict': False},
              'holds/nlp.hold.verb': {'3': False,
                                      '4': False,
                                      'actor': False,
                                      'claim': False,
                                      'conflict': False},
              'releases/nlp.release.verb': {'3': False,
                                            '4': False,
                                            'actor': False,
                                            'claim': False,
                                            'conflict': False},
              'loses/nlp.lose.verb': {'3': False,
                                      '4': False,
                                      'actor': False,
                                      'claim': False,
                                      'conflict': False},
              'backs/nlp.back.verb': {'3': False,
                                      '4': False,
                                      'actor': False,
                                      'claim': False,
                                      'conflict': False},
              'rises/nlp.rise.verb': {'3': False,
                                      '4': False,
                                      'actor': False,
                                      'claim': False,
                                      'conflict': False},
              'have/nlp.have.verb': {'3': False,
                                     '4': False,
                                     'actor': False,
                                     'claim': False,
                                     'conflict': False},
              'detained/nlp.detain.verb': {'3': False,
                                           '4': False,
                                           'actor': False,
                                           'claim': False,
                                           'conflict': False},
              'clash/nlp.clash.verb': {'3': True,
                                       '4': False,
                                       'actor': True,
                                       'claim': False,
                                       'conflict': True},
              'puts/nlp.put.verb': {'3': False,
                                    '4': False,
                                    'actor': False,
                                    'claim': False,
                                    'conflict': False},
              'attacked/nlp.attack.verb': {'3': False,
                                           '4': False,
                                           'actor': False,
                                           'claim': False,
                                           'conflict': False},
              'call/nlp.call.verb': {'3': True,
                                     '4': False,
                                     'actor': True,
                                     'claim': False,
                                     'conflict': False},
              'tells/nlp.tell.verb': {'3': False,
                                      '4': False,
                                      'actor': False,
                                      'claim': False,
                                      'conflict': False},
              'turns/nlp.turn.verb': {'3': False,
                                      '4': False,
                                      'actor': False,
                                      'claim': False,
                                      'conflict': False},
              'face/nlp.face.verb': {'3': False,
                                     '4': False,
                                     'actor': False,
                                     'claim': False,
                                     'conflict': False},
              'admits/nlp.admit.verb': {'3': True,
                                        '4': False,
                                        'actor': True,
                                        'claim': False,
                                        'conflict': False},
              'unveils/nlp.unveil.verb': {'3': True,
                                          '4': True,
                                          'actor': True,
                                          'claim': False,
                                          'conflict': False},
              'seizes/nlp.seize.verb': {'3': False,
                                        '4': False,
                                        'actor': False,
                                        'claim': False,
                                        'conflict': False},
              'comes/nlp.come.verb': {'3': False,
                                      '4': False,
                                      'actor': False,
                                      'claim': False,
                                      'conflict': False},
              'strikes/nlp.strike.verb': {'3': False,
                                          '4': False,
                                          'actor': False,
                                          'claim': False,
                                          'conflict': False},
              'agree/nlp.agree.verb': {'3': True,
                                       '4': True,
                                       'actor': True,
                                       'claim': False,
                                       'conflict': False},
              'executes/nlp.execute.verb': {'3': False,
                                            '4': False,
                                            'actor': False,
                                            'claim': False,
                                            'conflict': False},
              'warn/nlp.warn.verb': {'3': True,
                                     '4': True,
                                     'actor': True,
                                     'claim': False,
                                     'conflict': True},
              'set/nlp.set.verb': {'3': False,
                                   '4': False,
                                   'actor': False,
                                   'claim': False,
                                   'conflict': False},
              'injured/nlp.injure.verb': {'3': False,
                                          '4': False,
                                          'actor': False,
                                          'claim': False,
                                          'conflict': False},
              'show/nlp.show.verb': {'3': False,
                                     '4': False,
                                     'actor': False,
                                     'claim': False,
                                     'conflict': False},
              'demands/nlp.demand.verb': {'3': True,
                                          '4': False,
                                          'actor': True,
                                          'claim': False,
                                          'conflict': False},
              'fired/nlp.fire.verb': {'3': False,
                                      '4': False,
                                      'actor': False,
                                      'claim': False,
                                      'conflict': False},
              'meets/nlp.meet.verb': {'3': False,
                                      '4': False,
                                      'actor': False,
                                      'claim': False,
                                      'conflict': False},
              'protest/nlp.protest.verb': {'3': False,
                                           '4': False,
                                           'actor': False,
                                           'claim': False,
                                           'conflict': False},
              'cancels/nlp.cancel.verb': {'3': False,
                                          '4': False,
                                          'actor': False,
                                          'claim': False,
                                          'conflict': False},
              "'s/nlp.have.verb": {'3': False,
                                   '4': False,
                                   'actor': False,
                                   'claim': False,
                                   'conflict': False}}


rules.globals['predicates'] = predicates


@rules.add_rule('(:predicates * * ...)')
def claim(_, edge, actions):
    if len(edge) < 3 or len(edge) > 4:
        return
    pred = edge[0]
    if not predicates[pred][str(len(edge))]:
        return
    orig_actor = edge[1]
    if predicates[pred]['claim']:
        for concept in edge[2:]:
            mention = ('mention/gb.inf', orig_actor, concept)
            actions.create(mention)
            actions.create(('source/gb.inf', mention, edge))
    if predicates[pred]['conflict'] and len(edge) > 3:
            targ_actor = edge[2]
            for concept in edge[3:]:
                conflict = ('conflict/gb.inf', orig_actor, targ_actor, concept)
                actions.create(conflict)
                actions.create(('source/gb.inf', conflict, edge))


if __name__ == '__main__':
    hg = init_hypergraph('reddit-worldnews-01012013-01082017-new.hg')
    rules.apply_to(hg, dry_run=True)
